development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] || "mongodb://localhost/imminence_development" %>
      options:
        write:
          w: 1
        read:
          mode: :primary
  options:
    # This is more consistent with ActiveRecord
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV['TEST_MONGODB_URI'] || "mongodb://localhost/imminence_test" %>
      options:
        write:
          w: 1
        read:
          mode: :nearest
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
  options:
    # This is more consistent with ActiveRecord
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        write:
          w: 1
        read:
          mode: :nearest
        retry_interval: 120
  options:
    # This is more consistent with ActiveRecord
    raise_not_found_error: false
