# Pact verify workflow
#
# This workflow asserts that Pact contract tests are valid against this
# codebase. It is trigged when changes are made to this project and it
# is explicitly called by GDS API Adapters when changes are made there.

name: Run Pact tests

on:
  workflow_call:
    inputs:
      commitish:
        required: false
        type: string
        default: main
      pact_consumer_version:
        required: false
        type: string
        default: branch-main

jobs:
  pact_verify:
    name: Verify pact tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:14-master
        ports: ["5432:5432"]
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      PACT_CONSUMER_VERSION: ${{ inputs.pact_consumer_version }}
      TEST_DATABASE_URL: postgis://postgres@localhost/test-db
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
        with:
          repository: alphagov/imminence
          ref: ${{ inputs.commitish }}
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rails db:setup
      - run: bundle exec rake pact:verify
